spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/Food_Ordering_db
    username: food_user
    password: foodie123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

server:
  port: 8080