spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/food_ordering
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
server:
  port: 8080
